#!/bin/bash

DEVICE=/dev/ttyS0
SPEED=115200

case "$1" in
on)
    rt stty -F $DEVICE $SPEED
    ;;
off)
    rt stty -F $DEVICE 0 2>/dev/null
    ;;
reset)
    rt stty -F $DEVICE 0 2>/dev/null
    sleep 1
    rt stty -F $DEVICE $SPEED
    ;;
toggle)
    if (( $(rt stty -F $DEVICE speed) == 0 )); then
	rt stty -F $DEVICE $SPEED
    else
	rt stty -F $DEVICE 0 2>/dev/null
    fi
    ;;
esac

exit 0
